<a href="https://colab.research.google.com/github/tech-david/DSC550-Spring22/blob/main/Topic5/DSC550Topic5Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Load data
prototypes = {
    "Banana": [-1, -1, 1],
    "Pineapple": [-1, 1, -1]
}

In [3]:
# Training parameters
n_train = 2
# Number of test sets
n_test = 100
# Set distortion for randomness
distort = 0.1
# Number of neurons
n_neurons = 3

In [4]:
train_data = [np.array(x) for x in prototypes.values()][:n_train]

In [5]:
print(train_data)

[array([-1, -1,  1]), array([-1,  1, -1])]


In [6]:
# Creating random test set
test_data = []
for x in range(n_test):
    r = np.random.randint(0, n_train)
    test_instances = np.array(train_data[r])
    noise = 1 * (np.random.random(test_instances.shape) > distort)
    np.place(noise, noise == 0, -1)
    noisy_instances = np.multiply(test_instances, noise)
    test_data.append((test_instances, noisy_instances))

In [7]:
print(test_data)

[(array([-1, -1,  1]), array([-1, -1,  1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1,  1, -1]), array([-1,  1,  1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1, -1,  1]), array([-1, -1,  1])), (array([-1,  1, -1]), array([-1,  1, -1])), (array([-1,  1, -1]), array([-1

In [8]:
def train(neuron, training_data):
    w = np.zeros([neuron, neuron])
    for data in training_data:
        w += np.outer(data, data)
    for weight_value in range(neuron):
        w[weight_value][weight_value] = 0
    print(w)
    return w

In [9]:
def test(weights, testing_data):
    success = 0.0

    output = []

    for data in testing_data:
        true = data[0]
        noisy = data[1]
        predicted = get_pattern(weights, noisy)
        if np.array_equal(true, predicted):
            success += 1.0
        output.append([true, noisy, predicted])

    print(output)

    return (success / len(testing_data)), output

In [10]:
def get_pattern(weights, data, steps=10):
    result = np.array(data)

    for _ in range(steps):
        for i in range(len(result)):
            j = np.dot(weights[i], result)
            # Creating hardlim
            if j > 0:
                result[i] = 1
            else:
                result[i] = -1

    print(result)
    return result

In [11]:
# Train
W = train(n_neurons, train_data)

[[ 0.  0.  0.]
 [ 0.  0. -2.]
 [ 0. -2.  0.]]


In [12]:
print(W)

[[ 0.  0.  0.]
 [ 0.  0. -2.]
 [ 0. -2.  0.]]


In [13]:
# Test
accuracy, output = test(W, test_data)

[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1  1 -1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]
[-1  1 -1]
[-1 -1  1]
[-1  1 -1]

In [14]:
print("Accuracy of the network is %.2f" % (accuracy * 100))

Accuracy of the network is 93.00


In [15]:
# print output classifications of test data
for i in range(len(output)):
    for j in range(len(list(prototypes.keys()))):
        if all(output[i][2] == list(prototypes.values())[j]):
            print(i, list(prototypes.keys())[j])

0 Banana
1 Pineapple
2 Pineapple
3 Banana
4 Pineapple
5 Banana
6 Pineapple
7 Pineapple
8 Banana
9 Pineapple
10 Pineapple
11 Pineapple
12 Banana
13 Banana
14 Banana
15 Banana
16 Banana
17 Banana
18 Banana
19 Pineapple
20 Banana
21 Pineapple
22 Pineapple
23 Banana
24 Pineapple
25 Banana
26 Banana
27 Pineapple
28 Pineapple
29 Banana
30 Banana
31 Pineapple
32 Banana
33 Pineapple
34 Banana
35 Pineapple
36 Banana
37 Banana
38 Banana
39 Banana
40 Pineapple
41 Pineapple
42 Pineapple
43 Banana
44 Banana
45 Banana
46 Pineapple
47 Banana
48 Banana
49 Pineapple
50 Pineapple
51 Banana
52 Pineapple
53 Banana
54 Banana
55 Banana
56 Banana
57 Pineapple
58 Banana
59 Banana
60 Banana
61 Banana
62 Banana
63 Banana
64 Pineapple
65 Banana
66 Banana
67 Banana
68 Banana
69 Pineapple
70 Banana
71 Pineapple
72 Banana
73 Pineapple
74 Banana
75 Pineapple
76 Pineapple
77 Banana
78 Banana
79 Banana
80 Banana
81 Pineapple
82 Pineapple
83 Pineapple
84 Pineapple
85 Pineapple
86 Banana
87 Pineapple
88 Pineapple
89 Ban